[workspace]
name = "jupyterlab"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
jupyterlab = ">=4.0,<5"

[tool.capability]
spec-version = 1

[tool.capability.jupyterlab]
name = "JupyterLab"
description = "A minimal JupyterLab capability"
icon = "https://raw.githubusercontent.com/jupyterlab/jupyterlab/refs/heads/main/docs/source/_static/jupyter_logo.svg"
author = { name = "OpenTeams", email = "info@openteams.com" }

[tasks]
launch = { cmd = "jupyter lab $1" }
